name: Welcome New Contributors

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        uses: actions/first-interaction@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          issue-message: "👋 Thank you for opening your first issue! We appreciate your contribution and will review it soon. 🚀"
          pr-message: "🎉 Welcome to the project! Thank you for your first pull request. Please check our [contribution guidelines](https://github.com/your-repo/CONTRIBUTING.md)."
